### ISSUE TITLE
[BUG]: Crash on start Script error

### ISSUE THREAD

**Issue by davros-** [nltp-ashes/Western-Goods#42]
### Description

crashes on start, adjusted the priority still crashes.

snotrocket from moddb.com

### Addon version

v2.4.0

### Game version

1.5.2

### Log output

! [SCRIPT ERROR]: d:/anomaly\gamedata\scripts\western_goods_utils.script:463: attempt to call method 'ParseDirFile' (a nil value)

FATAL ERROR

[error]Expression : <no expression>
[error]Function : CScriptEngine::lua_error
[error]File : ..\xrServerEntities\script_engine.cpp
[error]Line : 191
[error]Description : fatal error
[error]Arguments : LUA error: d:/anomaly\gamedata\scripts\western_goods_utils.script:463: attempt to call method 'ParseDirFile' (a nil value)

### Contact

jasonstrait@gmail.com

### Confirmation

- [X] Yes, I have.

**Comment by davros-** [comment]
[xray_snotrocket.log](https://github.com/nltp-ashes/Western-Goods/files/13605017/xray_snotrocket.log)

**Comment by davros-** [comment]
but i am? every other addon works hmmm interesting, are the modded exes different than the ones on site?

**Comment by nltp-ashes** [comment]
Yes, the modded exes are their own thing.

If you're using JSGME, you can install them as any other addon.

If you're using MO2, you should install the bin folder manually (without a mod manager), and the rest of the files like any other addons.

**Comment by davros-** [comment]
just applied said modded exe's and all is well THANK YOU so much !!!

**Comment by nltp-ashes** [comment]
Nice, glad we got it resolved :) Enjoy the addon.
