### ISSUE TITLE
[BUG]: western_goods_utils.script:828: attempt to index a nil value

### ISSUE THREAD

**Issue by AnthonyIrw1n** [nltp-ashes/Western-Goods#67]
### Description

Tried to talk to a trader using Neutral Trader's mod, got a crash in img
![image](https://github.com/nltp-ashes/Western-Goods/assets/166643088/8264eb02-578f-4936-bd83-faa4ccaec6d1)

### Addon version

v2.3.0

### Game version

1.5.2

### Log output

NPC esc_3_16_military_trader has no trade information
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script(828) : get_real_community
! [LUA]  2 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(39) : spawn_western_goods_in_trader
! [LUA]  3 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(57) : TraderAuto
! [LUA]  4 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script(15) : update
! [LUA]  5 : [Lua] ...nomaly-1.5.1.2\gamedata\scripts\trader_autoinject.script(53) : f
! [LUA]  6 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(373) : functor_a
! [LUA]  7 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(461) : 
! [LUA] SCRIPT RUNTIME ERROR
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script(828) : get_real_community
! [LUA]  2 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(39) : spawn_western_goods_in_trader
! [LUA]  3 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(57) : TraderAuto
! [LUA]  4 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script(15) : update
! [LUA]  5 : [Lua] ...nomaly-1.5.1.2\gamedata\scripts\trader_autoinject.script(53) : f
! [LUA]  6 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(373) : functor_a
! [LUA]  7 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(461) : 
! [LUA] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script:828: attempt to index a nil value
! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script(828) : get_real_community
! [LUA]  2 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(39) : spawn_western_goods_in_trader
! [LUA]  3 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(57) : TraderAuto
! [LUA]  4 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script(15) : update
! [LUA]  5 : [Lua] ...nomaly-1.5.1.2\gamedata\scripts\trader_autoinject.script(53) : f
! [LUA]  6 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(373) : functor_a
! [LUA]  7 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(461) : 
! [SCRIPT ERROR]: ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script:828: attempt to index a nil value
 
FATAL ERROR
 
[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[error]Line          : 262
[error]Description   : fatal error
[error]Arguments     : 
 1 : [Lua] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script(828) : get_real_community
 
LUA error: ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script:828: attempt to index a nil value
 
Check log for details
 

stack trace:

! [LUA]  0 : [C  ] __index
! [LUA]  1 : [Lua] ...maly-1.5.1.2\gamedata\scripts\western_goods_utils.script(828) : get_real_community
! [LUA]  2 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(39) : spawn_western_goods_in_trader
! [LUA]  3 : [Lua] ...omaly-1.5.1.2\gamedata\scripts\western_goods_core.script(57) : TraderAuto
! [LUA]  4 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\wpo_loot.script(15) : update
! [LUA]  5 : [Lua] ...nomaly-1.5.1.2\gamedata\scripts\trader_autoinject.script(53) : f
! [LUA]  6 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(373) : functor_a
! [LUA]  7 : [Lua] d:/games/anomaly-1.5.1.2\gamedata\scripts\_g.script(461) : 

### Contact

Discord: @AnthonyIrwin

### Confirmation

- [X] Yes, I have.

**Comment by nltp-ashes** [comment]
Hi @AnthonyIrw1n, thanks a lot for submitting the issue. It helps me and other people in the future who might encounter the same issue as you.

Could you try to reinstall the addon? Make sure to **delete all the files from the current version** of the addon that you use, and reinstall it completely.

I see you don't use the latest version of the addon. If possible, try to update to the [latest version](https://github.com/nltp-ashes/Western-Goods/releases/latest), if not, you can get v2.3.0 from [here](https://github.com/nltp-ashes/Western-Goods/releases/tag/v2.3.0).

**Comment by nltp-ashes** [comment]
Also @AnthonyIrw1n, could you please drag and drop your entire log file in the GitHub textbox, this way I would have more information about what happened. Thanks !

**Comment by AnthonyIrw1n** [comment]
update: issue was caused by incorrect respawning of trader
