### ISSUE TITLE
[BUG]: western_goods_bind_lighter.script:246: attempt to index local 'obj' (a nil value)

### ISSUE THREAD

**Issue by NamelessNarrator** [nltp-ashes/Western-Goods#76]
### Description

So i was testing my new addons in the test level (F2) , and then i tested the new devices, everything worked perfectly until i tried the new lighter and it crashed.

### Addon version

v2.6.0

### Game version

1.5.2

### Game execution log

[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[error]Line          : 257
[error]Description   : fatal error
[error]Arguments     : 
 1 : [Lua] ...omaly\gamedata\scripts\western_goods_bind_lighter.script(246) : 
 
LUA error: ...omaly\gamedata\scripts\western_goods_bind_lighter.script:246: attempt to index local 'obj' (a nil value)
 
Check log for details
 

stack trace:

### Contact

Discord @nameless___narrator1

### Confirmation

- [X] Yes, I have read the instructions and have all the pre-requisites installed.

**Comment by NamelessNarrator** [comment]
Update : It also crashed when i tried using the Blue Lighter too



[error]Expression    : <no expression>
[error]Function      : CScriptEngine::lua_pcall_failed
[error]File          : D:\a\xray-monolith\xray-monolith\src\xrServerEntities\script_engine.cpp
[error]Line          : 257
[error]Description   : fatal error
[error]Arguments     : 
 1 : [Lua] ...omaly\gamedata\scripts\western_goods_bind_lighter.script(246) : 
 
LUA error: ...omaly\gamedata\scripts\western_goods_bind_lighter.script:246: attempt to index local 'obj' (a nil value)
 
Check log for details
 

stack trace:

:(

**Comment by nltp-ashes** [comment]
Hello @NamelessNarrator,

Can you please drag and drop your log file itself in the text box? The extract you sent does not give sufficient details about the error you got :(

Thanks in advance.

**Comment by NamelessNarrator** [comment]
> Hello @NamelessNarrator,
> 
> Can you please drag and drop your log file itself in the text box? The extract you sent does not give sufficient details about the error you got :(
> 
> Thanks in advance.


Its 23:51 , and I have an exam tommorow, I'll send it as soon as I can - thank you 🙃

**Comment by NamelessNarrator** [comment]
> Hello @NamelessNarrator,
> 
> Can you please drag and drop your log file itself in the text box? The extract you sent does not give sufficient details about the error you got :(
> 
> Thanks in advance.

-
This is the log with the Blue Lighter
[Uploading xray_user2.log…]()

**Comment by nltp-ashes** [comment]
Hello @NamelessNarrator,

I think you sent the file before it was done uploading...

**Comment by NamelessNarrator** [comment]
> Hello @NamelessNarrator,
> 
> I think you sent the file before it was done uploading...

Im a little stupid

**Comment by NamelessNarrator** [comment]
[xray_user2.log](https://github.com/nltp-ashes/Western-Goods/files/15447602/xray_user2.log)

**Comment by nltp-ashes** [comment]
Thank you.

As I suspected, your game executables are out of date.
```
'xrCore' build 9061, Nov 28 2023
```
Can you please [update them](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/releases/tag/2024.05.23) and check if the issue persists?

**Comment by NamelessNarrator** [comment]
> Thank you.
> 
> As I suspected, your game executables are out of date.
> 
> ```
> 'xrCore' build 9061, Nov 28 2023
> ```
> 
> Can you please [update them](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/releases/tag/2024.05.23) and check if the issue persists?

Aight, give me like half a hour :_:

**Comment by NamelessNarrator** [comment]
> Thank you.
> 
> As I suspected, your game executables are out of date.
> 
> ```
> 'xrCore' build 9061, Nov 28 2023
> ```
> 
> Can you please [update them](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes/releases/tag/2024.05.23) and check if the issue persists?

I was sure i updated them though

**Comment by NamelessNarrator** [comment]
Downloaded and installed, gon test rn

**Comment by NamelessNarrator** [comment]
@nltp-ashes Everything works perfectly now !! THANK YOU !!! 😃

**Comment by nltp-ashes** [comment]
Glad your issue is resolved. In the future, please double check that you do have the addon's requirements installed **and up-to-date**.
