### ISSUE TITLE
Devices : Marking stashes using the GPS Locator

### ISSUE THREAD

**Issue by Lexus2411** [nltp-ashes/Western-Goods#77]
### Abstract

!NEW!  GPS leaves a location mark in the box
![Без названия](https://github.com/nltp-ashes/Western-Goods/assets/170987637/9af7230b-ab07-4086-861e-2c6c1ec1c762)

### Importance

5 - Absolutely necessary

### Description

It would be cool if the new GPS item from update 2.6.0 had the ability to display a tag in the data storage when inserting it into any box, this ability is most suitable for him, because this is his area of activity.

It would be desirable for the tag to have an individual color ;)

### Contact

Discord: @lexus_lesha

**Comment by nltp-ashes** [comment]
Hi @Lexus2411,

Thanks for creating the issue. I was worried I would forget if it wasn't somewhere I check frequently.

I'll update this issue when I start working on this ;)

**Comment by nltp-ashes** [comment]
Hi @Lexus2411,

Development on your suggestions was completed, and the new content will be available in the next update.

Implementing this feature required engine modifications, so you will need to make sure your [modded executables](https://github.com/themrdemonized/STALKER-Anomaly-modded-exes) are up-to-date when the update releases.

![image](https://github.com/user-attachments/assets/fca47802-eb11-48db-b37f-d9388bf962ee)

Thank you again for your suggestion.

I will be closing the issue. Don't hesitate to re-open it if you'd like to add to the idea, or open a new one if you'd like to make another suggestion !
