### ISSUE TITLE
Guides : Revision of the prices of the guides travel

### ISSUE THREAD

**Issue by Rambito1** [nltp-ashes/Western-Goods#81]
### Abstract

Revision of the prices of the guides travel from Yanov to AW and the helicopters rides from/to Yantar

### Importance

0 - Not needed at all

### Description

I think you should increase the price for the guide from Yanov to AW, now is 4k, in contrast; the vanilla price from AW to Yanov is 6k, also the price of the helicopter ride from Yantar to Jupiter should be around 10-12k
For sake of consistency and balance

**Comment by Rambito1** [comment]
Sorry for suggesting this after closing the request, but can you add route from the bandit base at dark valley to the bandit base at the containers in Jupiter, both ways?

Jupiter base have no guide so it can be the trader, he seems to be the boss over there.

The price I will suggest at 12K+

**Comment by nltp-ashes** [comment]
Hi @Rambito1,

Development on your suggestions was completed, and the new content will be available in the next update.

As a reminder, here is what was implemented :
- Changed guide price from Yanov to Army Warehouses from **4k RUB** to **6k RUB**;
- Changed guide price from Yanov to Yantar from **8k RUB** to **12k RUB**;
- Changed guide price from Yantar to Yanov from **8k RUB** to **12k RUB**;
- Added route from container warehouse in Jupiter to Bandit base in Dark Valley for **8k RUB**;
- Added route from Bandit base in Dark Valley to Renegade base in Great Swamps for **3k RUB**.

Thank you again for your suggestion. 

I will be closing the issue. Don't hesitate to re-open it if you'd like to add to the idea, or open a new one if you'd like to make another suggestion !
