### ISSUE TITLE
[CHANGE]: Flea Market - Rebalance item pool for GAMMA

### ISSUE THREAD

**Issue by Pillii** [nltp-ashes/Western-Goods#88]
### Abstract

Delete certain items from the pool to match GAMMA's intended progression.

### Importance

3 - Nice but not required

### Description

Delete the following items: 
ammo_vog-25
ammo_gauss
ammo_m209
toolkit_p
toolkit_r5
toolkit_r7
toolkit_s
medium_repair_kit
heavy_repair_kit
exo_repair_kit
light_repair_kit
cleaning_kit_u

### Contact

Discord: pillii

**Comment by nltp-ashes** [comment]
Hello @Pillii,

Thank you for creating this issue. It really helps me in my development of this addon.

Western Goods is an addon made first and foremost for vanilla S.T.A.L.K.E.R. Anomaly. This means that re-balancing the Flea Market system's loot pool to play better with the G.A.M.M.A mod-pack is not reasonable.

That being said, I have created a [patch](https://github.com/nltp-ashes/Western-Goods/releases/tag/patch-flea-gamma) that you can download and install alongside Western Goods. This patch will remove the items you mentioned from the Flea Market system's loot pool.

I will be closing the issue. In the event that this patch doesn't solve this situation, feel free to re-open the issue
