### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Archangel47-hub** [nltp-ashes/Western-Goods#99]
### Description

I was loading a save that had been working fine to this point, and I got a fatal 262 error but it wasn't ZLM related, at least what I could see. It said something about Get_magazine_caliber as a part of the error. i had already reinstalled FDDA without the western goods patch by this point.

### Addon version

v3.1.0

### Game version

1.5.3

### Game execution log

[xray_maste.log](https://github.com/user-attachments/files/17892180/xray_maste.log)

### Contact

Archangel47

### Confirmation

- [X] Yes, I have read the instructions and have all the pre-requisites installed.

**Comment by Archangel47-hub** [comment]
Ah, I messed up; my discord is Archangel47 for contact. I forgot to fill out the field after i retrieved and attached the log file. Totally my fault.

**Comment by nltp-ashes** [comment]
Hello @Archangel47-hub,

Thank you for submitting this issue. Unfortunately, this error does not seem to be related to my addon. I recommend you seek help on Anomaly's official Discord server, in _#addons-support_.

I hope you find a fix for your error there.
